#ifndef __RSNRPZ_RESOURCE_H__
#define __RSNRPZ_RESOURCE_H__

#if ! defined (USE_AAV_PATCH)
#define VER_PRODUCTMAJORVERSION 3
#define VER_PRODUCTMINORVERSION 6
#define VER_BUILDMAJORVERSION   0
#define VER_BUILDMINORVERSION   1
#define VER_BUILDMONTH          7
#define VER_BUILDYEAR           2019
#else
#define VER_PRODUCTMAJORVERSION 3
#define VER_PRODUCTMINORVERSION 3
#define VER_BUILDMAJORVERSION   0
#define VER_BUILDMINORVERSION   0
#define VER_BUILDMONTH          4
#define VER_BUILDYEAR           2016
#endif

#endif  // __RSNRPZ_RESOURCE_H__
